### PR TITLE
[OHSS-10367] Swap to ubi8-minimal and update osde2e dependency to pull in upstream bug fixes

### PR DESCRIPTION
**Pull request by mjlshen**
https://issues.redhat.com/browse/OSD-10367 updating to latest will allow this job to succeed on newly created clusters since cloud-controller-manager reports statuses of `CloudConfigControllerAvailable` and `TrustedCABundleControllerControllerAvailable`

Latest relevant osde2e PR: https://github.com/openshift/osde2e/pull/1069

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Reasonable, just needs manual build & testing (because no CI) to make sure none of the APIs changed.

**Comment by mjlshen** [comment]
After https://github.com/openshift/osde2e/pull/1069 went in, I am now able to verify this works!
```
+ oc logs -f jobs/osd-cluster-ready -n openshift-monitoring
2022/03/17 16:57:35 ======== Health Checks: 1 of 20 ========
2022/03/17 16:57:35 Polling Cluster Health...
2022/03/17 16:57:35 Checking that CVO says the cluster is healthy...
2022/03/17 16:57:36 Checking that all Nodes are running or completed...
2022/03/17 16:57:36 Checking that machines are healthy...
2022/03/17 16:57:36 Checking that all Operators are running or completed...
2022/03/17 16:57:36 Checking that all Pods are running or completed...
2022/03/17 16:57:36 7 pods are currently not running or complete:
2022/03/17 16:57:36 Certificate(s) has been found.
2022/03/17 16:57:36 Checking that all Daemonsets are running with expected replicas...
2022/03/17 16:57:36 Checking that all Replicasets are running with expected replicas...
2022/03/17 16:57:36 Health checks succeeded.
2022/03/17 16:57:36 Sleeping 30 seconds...
```

**Comment by 2uasimojo** [comment]
otherwise LGTM!

**Comment by iamkirkbater** [comment]
LGTM

**Pull request merged**
